#!/bin/bash

set -e
set -u

function create_user_and_database() {
    local database=$1
    local user=$2
    local password=$3
    echo "Creating user '$user' and database '$database'"
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "postgres" <<-EOSQL
        CREATE USER $user WITH REPLICATION PASSWORD '$password';
        ALTER USER $user WITH SUPERUSER;
        CREATE DATABASE $database WITH OWNER $user;
EOSQL

    if [ "$database" = "db3" ]; then
        echo "Creating table paypal_outbox_events in database '$database'"
        psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$database" <<-EOSQL
            CREATE TABLE paypal_outbox_events
            (
                id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                paypal_token   VARCHAR(255) NOT NULL,
                CONSTRAINT pk_paypal_outbox_events PRIMARY KEY (id)
            );
EOSQL
    fi
}

if [ -n "${POSTGRES_MULTIPLE_DATABASES:-}" ]; then
    echo "Multiple database creation requested: $POSTGRES_MULTIPLE_DATABASES"
    for db_config in $(echo $POSTGRES_MULTIPLE_DATABASES | tr ',' ' '); do
        IFS=':' read -r db user password <<< "$db_config"
        create_user_and_database $db $user $password
    done
    echo "Multiple databases created"
fi