CREATE TABLE payment
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reservation_id    BIGINT                                  NOT NULL,
    status            VARCHAR(255),
    payment_amount    DOUBLE PRECISION                        NOT NULL,
    paypal_order_id   VARCHAR(255),
    paypal_payment_id VARCHAR(255),
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    payment_date      TIMESTAMP WITHOUT TIME ZONE,
    version           BIGINT                                  NOT NULL,
    CONSTRAINT pk_payment PRIMARY KEY (id)
);

ALTER TABLE payment
    ADD CONSTRAINT uc_payment_paypalorderid UNIQUE (paypal_order_id);