CREATE TABLE customer
(
    generic_user_data_id BIGINT  NOT NULL,
    date_of_birth        date,
    reliability_scores   INTEGER NOT NULL,
    driving_license      VARCHAR(255),
    expiration_date      date,
    CONSTRAINT pk_customer PRIMARY KEY (generic_user_data_id)
);

CREATE TABLE employee
(
    generic_user_data_id BIGINT           NOT NULL,
    role_id              BIGINT,
    salary               DOUBLE PRECISION NOT NULL,
    CONSTRAINT pk_employee PRIMARY KEY (generic_user_data_id)
);

CREATE TABLE generic_user
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255),
    surname VARCHAR(255),
    email   VARCHAR(255),
    phone   VARCHAR(255),
    address VARCHAR(255),
    city    VARCHAR(255),
    CONSTRAINT pk_genericuser PRIMARY KEY (id)
);

CREATE TABLE role
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name_role VARCHAR(255),
    CONSTRAINT pk_role PRIMARY KEY (id)
);

ALTER TABLE customer
    ADD CONSTRAINT FK_CUSTOMER_ON_GENERICUSERDATA FOREIGN KEY (generic_user_data_id) REFERENCES generic_user (id);

ALTER TABLE employee
    ADD CONSTRAINT FK_EMPLOYEE_ON_GENERICUSERDATA FOREIGN KEY (generic_user_data_id) REFERENCES generic_user (id);

ALTER TABLE employee
    ADD CONSTRAINT FK_EMPLOYEE_ON_ROLE FOREIGN KEY (role_id) REFERENCES role (id);