
CREATE TABLE reservation
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id      BIGINT                                  NOT NULL,
    employee_id      BIGINT                                  NOT NULL,
    vehicle_id       BIGINT,
    status_id        BIGINT,
    reservation_date TIMESTAMP WITHOUT TIME ZONE,
    start_date       TIMESTAMP WITHOUT TIME ZONE,
    end_date         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_reservation PRIMARY KEY (id)
);


CREATE TABLE status
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status VARCHAR(255),
    CONSTRAINT pk_status PRIMARY KEY (id)
);


ALTER TABLE reservation
    ADD CONSTRAINT FK_RESERVATION_ON_STATUS FOREIGN KEY (status_id) REFERENCES status (id);

ALTER TABLE reservation
    ADD CONSTRAINT FK_RESERVATION_ON_VEHICLE FOREIGN KEY (vehicle_id) REFERENCES vehicle (id);

