CREATE TABLE paypal_outbox_events
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    paypal_token VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_paypal_outbox_events PRIMARY KEY (id)
);

ALTER TABLE reservation
    ADD payment_amount DOUBLE PRECISION;

ALTER TABLE reservation
    ALTER COLUMN payment_amount SET NOT NULL;